using System.IO.Compression;
using System.Text;

namespace NapisyPL.Core.ContextResolution;

/// <summary>
/// Masculine/feminine form pairs derived from the SGJP dictionary (Morfeusz 2
/// project, BSD 2-clause), generated by tools/gender-lexicon/build_gender_lexicon.py.
///
/// Replaces a hand-kept list of about seventy verb stems: a correction such as
/// "wyjaśniłem -> wyjaśniłam" used to be silently skipped because the stem was not
/// on the list. The generator already removed forms that are also a noun or a
/// present-tense verb ("wysyłam", "gram"), so a lookup here is a safe rewrite.
/// </summary>
public sealed class GenderFormLexicon
{
    private const string ResourceName = "gender_forms.sgjp.tsv.gz";
    private static readonly Lazy<GenderFormLexicon> DefaultInstance = new(LoadEmbedded);

    private GenderFormLexicon(
        Dictionary<string, string> selfMaleToFemale,
        Dictionary<string, string> selfFemaleToMale,
        Dictionary<string, string> addresseeMaleToFemale,
        Dictionary<string, string> addresseeFemaleToMale,
        Dictionary<string, string> predicateMaleToFemale,
        Dictionary<string, string> predicateFemaleToMale)
    {
        SelfMaleToFemale = selfMaleToFemale;
        SelfFemaleToMale = selfFemaleToMale;
        AddresseeMaleToFemale = addresseeMaleToFemale;
        AddresseeFemaleToMale = addresseeFemaleToMale;
        PredicateMaleToFemale = predicateMaleToFemale;
        PredicateFemaleToMale = predicateFemaleToMale;
    }

    public static GenderFormLexicon Default => DefaultInstance.Value;

    /// <summary>An empty lexicon, used when the resource cannot be read.</summary>
    public static GenderFormLexicon Empty { get; } = new([], [], [], [], [], []);

    /// <summary>First person singular past and conditional ("chciałem" -> "chciałam").</summary>
    public IReadOnlyDictionary<string, string> SelfMaleToFemale { get; }
    public IReadOnlyDictionary<string, string> SelfFemaleToMale { get; }

    /// <summary>Second person singular past and conditional ("chciałeś" -> "chciałaś").</summary>
    public IReadOnlyDictionary<string, string> AddresseeMaleToFemale { get; }
    public IReadOnlyDictionary<string, string> AddresseeFemaleToMale { get; }

    /// <summary>Predicate adjectives and participles ("gotowy" -> "gotowa").</summary>
    public IReadOnlyDictionary<string, string> PredicateMaleToFemale { get; }
    public IReadOnlyDictionary<string, string> PredicateFemaleToMale { get; }

    public static GenderFormLexicon Parse(TextReader reader)
    {
        ArgumentNullException.ThrowIfNull(reader);

        var selfM = new Dictionary<string, string>(StringComparer.Ordinal);
        var selfF = new Dictionary<string, string>(StringComparer.Ordinal);
        var addresseeM = new Dictionary<string, string>(StringComparer.Ordinal);
        var addresseeF = new Dictionary<string, string>(StringComparer.Ordinal);
        var predicateM = new Dictionary<string, string>(StringComparer.Ordinal);
        var predicateF = new Dictionary<string, string>(StringComparer.Ordinal);

        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line[0] == '#')
                continue;

            var first = line.IndexOf('\t');
            var second = first < 0 ? -1 : line.IndexOf('\t', first + 1);
            if (second < 0)
                continue;

            var category = line.AsSpan(0, first);
            var masculine = line.Substring(first + 1, second - first - 1);
            var feminine = line[(second + 1)..];

            var (toFemale, toMale) = category switch
            {
                "self" => (selfM, selfF),
                "addressee" => (addresseeM, addresseeF),
                "predicate" => (predicateM, predicateF),
                _ => (null, null)
            };
            if (toFemale is null || toMale is null)
                continue;

            toFemale.TryAdd(masculine, feminine);
            toMale.TryAdd(feminine, masculine);
        }

        return new GenderFormLexicon(selfM, selfF, addresseeM, addresseeF, predicateM, predicateF);
    }

    /// <summary>Hand-written entries win over generated ones.</summary>
    public static IReadOnlyDictionary<string, string> Merge(
        IReadOnlyDictionary<string, string> overrides,
        IReadOnlyDictionary<string, string> generated)
    {
        var merged = new Dictionary<string, string>(generated, StringComparer.Ordinal);
        foreach (var pair in overrides)
            merged[pair.Key] = pair.Value;
        return merged;
    }

    private static GenderFormLexicon LoadEmbedded()
    {
        var assembly = typeof(GenderFormLexicon).Assembly;
        var name = assembly.GetManifestResourceNames()
            .FirstOrDefault(resource => resource.EndsWith(ResourceName, StringComparison.OrdinalIgnoreCase));
        if (name is null)
            return Empty;

        using var stream = assembly.GetManifestResourceStream(name);
        if (stream is null)
            return Empty;

        using var gzip = new GZipStream(stream, CompressionMode.Decompress);
        using var reader = new StreamReader(gzip, Encoding.UTF8);
        return Parse(reader);
    }
}
